FROM surnet/alpine-wkhtmltopdf:3.18.0-0.12.6-small as wkhtmltopdf
COPY ./frappe_bench-5.20.0-py3-none-any.whl /tmp/frappe_bench-5.20.0-py3-none-any.whl
COPY sites /home/frappe/frappe-bench/sites

FROM alpine:3.18

COPY --from=wkhtmltopdf /tmp/frappe_bench-5.20.0-py3-none-any.whl /tmp/frappe_bench-5.20.0-py3-none-any.whl
COPY --from=wkhtmltopdf /home/frappe/frappe-bench/sites /home/frappe/frappe-bench/sites
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /bin/wkhtmltopdf
WORKDIR /home/frappe/frappe-bench

RUN apk add --no-cache \
    sudo \
    supervisor \
    fail2ban \
    nginx \
    redis \
    curl \
    git \
    vim \
    gettext \
    libpq \
    postgresql-client \
    mariadb-client \
    py3-pip \
    nodejs \
    npm \
    yarn \
    gcc \
    python3-dev \
    musl-dev \
    linux-headers \
    libstdc++ \
    libx11 \
    libxrender \
    libxext \
    libssl1.1 \
    ca-certificates \
    fontconfig \
    freetype \
    ttf-dejavu \
    ttf-droid \
    ttf-freefont \
    ttf-liberation \
    # Add
    wget \
    libffi-dev \
    libjpeg-turbo-dev \
    openldap-dev \
    mariadb-dev \
    cyrus-sasl-dev \
    tiff-dev \
    libwebp-dev \
    redis \
    build-base \
    bzip2-dev \
    && apk add --no-cache --virtual .build-deps \
    msttcorefonts-installer \
    \
    # Install microsoft fonts
    && update-ms-fonts \
    && fc-cache -f \
    \
    # Clean up when done
    && apk del .build-deps \
    && pip3 install /tmp/frappe_bench-5.20.0-py3-none-any.whl \
    && rm -rf /tmp/* \
    && rm -rf /var/cache/apk/* 

RUN bench init \
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --ignore-exist \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    /home/frappe/frappe-bench

CMD [ "sh" ]
