FROM surnet/alpine-wkhtmltopdf:3.18.0-0.12.6-small as wkhtmltopdf

FROM alpine:3.18

RUN apk add --no-cache \
  curl \
  git \
  vim \
  gettext \
  libpq \
  postgresql-client \
  mariadb-client \
  py3-pip \
  nodejs \
  npm \
  yarn \
  gcc \
  python3-dev \
  musl-dev \
  linux-headers \
  libstdc++ \
  libx11 \
  libxrender \
  libxext \
  libssl1.1 \
  ca-certificates \
  fontconfig \
  freetype \
  ttf-dejavu \
  ttf-droid \
  ttf-freefont \
  ttf-liberation \
  && apk add --no-cache --virtual .build-deps \
  msttcorefonts-installer \
  \
  # Install microsoft fonts
  && update-ms-fonts \
  && fc-cache -f \
  \
  # Clean up when done
  && rm -rf /tmp/* \
  && apk del .build-deps

COPY --from=wkhtmltopdf /bin/wkhtmltopdf /bin/wkhtmltopdf


ENTRYPOINT [ "sh" ]
